### ISSUE TITLE
Default profile launching after checking for updates with LibreWolf-WinUpdater

### ISSUE THREAD

**Issue by moya2162** [ltguillaume/librewolf-portable#12]
Appears default profile is launched even though a custom profile was specified at launch specifically when LibreWolf-WinUpdater is run prior to launching LibreWolf-Portable. In subsequent runs when the updater is not run to check for updates, the custom profile launches like normal. 

Appears LibreWolf-WinUpdater does not receive "-P" parameter from launcher and pass on after check for update. I was able to reproduce this effect consistently by deleting LibreWolf-WinUpdater.ini and launching a custom profile, only to have default open after update check.

**Comment by ltguillaume** [comment]
Thx for reporting! Yep, I forgot that I stripped the profile parameter from others in order to allow for both absolute paths and profile names only, so it wasn't passed to WinUpdater. Please try v1.6.0, see https://github.com/ltguillaume/librewolf-portable/releases/tag/1.6.0 to see if it's fixed.

**Comment by moya2162** [comment]
Issue appears to be fixed. 

-----------------------------

I have noticed a new issue now. It appears the "-P" parameter has changed. In order to launch a custom profile i usually use the following syntax:

`LibreWolf-Portable.exe -P "Profiles\Custom"`

Now, an additional profile folder is created within the profiles folder, which looks like:

`D:\LibreWolf\Profiles\Profiles\Custom`

If i modify my syntax to: 

`LibreWolf-Portable.exe -P "Custom"`

It correctly launches the "Custom" profile:

`D:\LibreWolf\Profiles\Custom`

This is a small nuanced change, of which i don't mind. Its easier in my opinion. If this was the intended behavior, please update the readme to reflect this behavior to minimize confusion.

**Comment by ltguillaume** [comment]
You're right! I forgot earlier to add the `Profiles\` automatically, so profiles were created in the main folder (unless the user worked around that by adding `Profiles\` themselves, like you did).

If the launcher finds the profile to be inside the main folder, then it moves it into the profiles folder. But in your case, with the added `Profiles\`, it moves it into `Profiles\Profiles`. I hadn't thought about that particular case, but it's a minor detail.

**Comment by ltguillaume** [comment]
Is it `prefs.js` or `prefs.js.pbak`? Can you tell me if the contents are just one line with `autoadmin.global_config_url`, or many?

I cannot reproduce this, sorry. It did point me to another minor thingy, so please check the new 1.6.0 prerelease https://github.com/ltguillaume/librewolf-portable/releases/tag/1.6.0

**Comment by moya2162** [comment]
1. prefs.js
2. Content is single line: 
`user_pref("autoadmin.global_config_url", "file:///C:/Users/.../LibreWolf/Profiles/Profiles/Work/librewolf.overrides.cfg");`

I will update my launcher with your newest version and report back if this issue is fixed on my end.

**Comment by moya2162** [comment]
I have yet to see the issue i described appear. I am going to say it is resolved.
