### ISSUE TITLE
Can't set Registry Key NativeMessagingHosts

### ISSUE THREAD

**Issue by 264-bit** [ltguillaume/librewolf-portable#13]
For the extension ff2mpv, I need to set HKEY_CURRENT_USER\Software\LibreWolf\NativeMessagingHosts.  Due to how this launcher is set up, it doesn't seem I can do this.  If I set this key while LibreWolf is running, it's ignored.  If I close it and set the key, then relaunch librewolf, the key is just moved into LibreWolf.pbak, it isn't present in LibreWolf.
Please allow setting/persisting this registry key somehow.  It seems to be the only way to adjust Native messaging hosts on Windows.

EDIT:  Disregard, the path seems to be hardcoded to HCU\Software\Mozilla even for LibreWolf.

**Comment by ltguillaume** [comment]
Ah, so you can use HCU\Software\Mozilla for this, which the launcher won't touch. I'm not aware of any other circumstances where a registry key/value inside the LibreWolf key should be set by the user, but if there is any, we can revisit this.
