### ISSUE TITLE
LibreWolf-Portable.exe updated by the LibreWolf Team

### ISSUE THREAD

**Issue by SimoLRepo** [ltGuillaume/LibreWolf-Portable#5]
Hi, since I noticed that the "LibreWolf-Portable.exe" executable present in the official downloads by LibreWolf differs in version, I wanted to ask if this project is still under development and whether the changes made by the LibreWolf team they are really useful. Thank you.

**Comment by ioc2e3** [comment]
Sorry , excuse me ...

Here ( https://codeberg.org/ltguillaume/librewolf-portable/releases ) provides the .zip archive of LibreWolf Portable ...

Why here ( https://github.com/ltguillaume/librewolf-portable/releases ) only provides the source code of LibreWolf Portable ...

.
