### ISSUE TITLE
Recommend adding launcher settings file

### ISSUE THREAD

**Issue by moya2162** [ltguillaume/librewolf-portable#7]
Currently portable launcher has directory settings hard coded into launcher which makes portable mode be less flexible for the user. 

`ProgramPath     := A_ScriptDir "\LibreWolf"`
`ExeFile         := ProgramPath "\librewolf.exe"`
`ProfilePath     := A_ScriptDir "\Profiles\Default"`

Recommend adding settings ini file next to launcher executable which would allow for changes to be made such that program path, executable file, and profile path can be changed. If possible this could allow for passing of launch parameters to be used as well. 

This idea was taken from the approach PortableApps has taken for their portable Firefox launcher. The main reason i like this is because i can easily create multiple profiles each with their own settings and extensions and i can just modify the launcher settings file to launch that profile. as needed. 

Example:

`LibreWolfDirectory=LibreWolf`
`ProfileDirectory=Profile\Default`
`LaunchParameters=-no-remote`

Chrlauncher also has a similar approach for portable chrome with its respective settings file. 

I'm not sure if this is possible but maybe a launch flag could be added to the LibreWolf launcher that allows for it to read a specific settings file within the directly, that way if people want to make custom shortcuts that launch specific profiles then it would be possible like so:

`"LibreWolf-Portable.exe" -LibreWolf-Portable.ini` (Default)
`"LibreWolf-Portable.exe" -LibreWolf-Portable-Tor.ini` (settings file modified to specifically launch a tor profile)

**Comment by ltGuillaume** [comment]
1. The profiles should be adjusted properly to have the extensions working. That is the primary function of the launcher 😅 So, was this issue only present when using the `-profile ...` argument, or does it also occur when you just copy the existing profile into `Profiles\Default`? Secondly, does this also occur with the stable launcher?
1. Yeah that's debug stuff I forgot to remove, sorry about that.
1. I'm still busy watching it (first time even), but I like it.

**Comment by ltGuillaume** [comment]
[LibreWolf-Portable_1.4.0TESTNODEBUG.zip](https://github.com/ltGuillaume/LibreWolf-Portable/files/10180600/LibreWolf-Portable_1.4.0TESTNODEBUG.zip)
Here's one without the debug nagging.
