### ISSUE TITLE
VirusTotal Flags as Malicious 

### ISSUE THREAD

**Issue by yoyogummy** [ltguillaume/librewolf-portable#8]
Would love to use this but 2 virus toltal scanners flag this as malware. Could be a false positive and if you could let me know your thoughts if this is a false positive or some verification that this is safe it would be great. 

I can't read code so I can't really tell if it is or not. 
 [https://www.virustotal.com/gui/file/f2509a3d4b459736798a30e1bd8dfe213c2da94e24e48de3ed6db19565afbd57/detection](url)

**Comment by ltGuillaume** [comment]
Yeah these false positives really are frustrating. You can read about it here:
- https://gitlab.com/librewolf-community/browser/windows/-/issues/315
- https://gitlab.com/librewolf-community/browser/windows/-/issues/317
