### ISSUE TITLE
Librewolf `librewolf.overrides.cfg` not load in portable windows version.

### ISSUE THREAD

**Issue by lessload** [ltguillaume/librewolf-portable#9]
I have place `librewolf.overrides.cfg` in `.\Profiles\Default\` but not load. refer to doc `https://librewolf.net/docs/settings/`<br/> 
But when i place it in `C:\Users\USERNAME\.librewolf\librewolf.overrides.cfg` it work fine.

Something wrong in portable version?

I already open issue in [here](https://gitlab.com/librewolf-community/browser/windows/-/issues/326)

**Comment by ltguillaume** [comment]
Can you tell me the value of `user_pref("autoadmin.global_config_url",...` in your profile's `prefs.js`?

**Comment by ltguillaume** [comment]
@lessload Any news?

**Comment by candrapersada** [comment]
how to use `librewolf.overrides.cfg` on LibreWolfPortable in `PortableApps.com`

**Comment by ltguillaume** [comment]
@candrapersada The release by PortableApps is neither created nor supported by me or anyone else from the LibreWolf (Windows) team, so I guess you'll have to ask them...

**Comment by ioc2e3** [comment]
> [@candrapersada](https://github.com/candrapersada)PortableApps 發布的版本不是由我或 LibreWolf（Windows）團隊的任何其他人創建或支援的， ...

...?

Always thought ...

was created or supported by you or anyone else from the LibreWolf ( Windows ) team ...

.
